import "./globals.css";
import type { Metadata } from "next";
import AuthProvider from "@/context/authProvider";
import { ThemeProvider } from "@/context/themeProvider";
import Provider from "@/context/queryProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toaster";
import Nav from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                    >
                        <div>
                            <Nav />
                            <main className="mt-20 mb-20">
                                <Provider>
                                    <TooltipProvider>
                                        {children}
                                    </TooltipProvider>
                                </Provider>
                            </main>
                        </div>
                        <Toaster />
                    </ThemeProvider>
                    <Footer />
                </AuthProvider>
            </body>
        </html>
    );
};
export default RootLayout;
